### ISSUE TITLE
否定論理和バッグ

### ISSUE THREAD

**Issue by Olivia-tou** [SBR2015/OoTalk_backend#114]
left:0 right:0　result:false
返す結果は間違った。trueで返すはず。

**Comment by yuchan** [comment]
なぜ間違ったと思うのかが重要な気がしますが、これ意外と深い問題で、プログラム的にrubyだと0はtrueなので、norの場合、真と真なので偽になります。我々の言語において、0をtrueとするかfalseとするかどうかは判断が必要です。

**Comment by a1447ll** [comment]
なるほど。そうすると0や１の引数ではなく、本当のtrueとfalseの値を返す式を入れた方がいいですね。

**Comment by Olivia-tou** [comment]
なるほど、rubyで0はtrueだ。普段で1はtrue、0はfalseで考えます。ootalkでは0、１何を表示しますか、あるいは表示しないか？
もし、rubyと同じで0はtrueだと、boolean類(true、falseの追加)がいるかな。
