### ISSUE TITLE
Constantのinputの背景色を入力前後で変化させる

### ISSUE THREAD

**Issue by yuchan** [SBR2015/OoTalk_backend#56]
入力前は赤（ピンク？）
入力後は白になるようにする。

placeholderも、@left, @rightから自然な言葉に変更。

**Comment by a1447ll** [comment]
`placeholderも、@left, @rightから自然な言葉に変更。`

ここはちょっと分からないです〜

**Comment by yuchan** [comment]
例えば、
@left -> 0,1,2,,

とかに変えて何を入力するのかわかるようにすると良いのではないかと思いました。
