### ISSUE TITLE
it doesn't work by firefox

### ISSUE THREAD

**Issue by chrhsmt** [SBR2015/OoTalk_backend#66]
[![Gyazo](https://i.gyazo.com/dfd7d117fbab9c0fa5a985e157c51eb4.gif)](https://gyazo.com/dfd7d117fbab9c0fa5a985e157c51eb4)

it doesn' work in firefox.
can not type in variable field.

**Comment by yuchan** [comment]
Thank you your attention.
we'll take care of it.
