### ISSUE TITLE
awesome ! lol

### ISSUE THREAD

**Issue by chrhsmt** [SBR2015/OoTalk_backend#67]
[![Gyazo](https://i.gyazo.com/e7625b99e885ec67b2d7bb614a6cfa6d.png)](https://gyazo.com/e7625b99e885ec67b2d7bb614a6cfa6d)

**Comment by a1447ll** [comment]
Haha  so you found this bug! We're trying to fix this asap! :D

**Comment by chrhsmt** [comment]
:+1:

**Comment by pyar6329** [comment]
Fixed already :)
